# Generated by Django 2.1.1 on 2018-09-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingdata',
            name='author',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parsingdata',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
